Section - A
 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [79]:
list=[45,78,90,23,89] #creating list of 5 integers.
print(list)


[45, 78, 90, 23, 89]


In [80]:
type(list) #printing type of list.


list

In [81]:
list.append(100) #performing append operation.
print(list)

[45, 78, 90, 23, 89, 100]


In [82]:
list.extend([200,300]) #performing extend operation.
print(list)

[45, 78, 90, 23, 89, 100, 200, 300]


In [83]:
list.insert(2,100)
print(list) #performing insert operation.

[45, 78, 100, 90, 23, 89, 100, 200, 300]


In [84]:
print(list)

[45, 78, 100, 90, 23, 89, 100, 200, 300]


In [85]:
list.remove(78) #performing remove operation.
print(list)

[45, 100, 90, 23, 89, 100, 200, 300]


In [86]:
list.pop() #performing pop operation.
print(list)

[45, 100, 90, 23, 89, 100, 200]


In [87]:
list.index(89) #printing index of element 89.


4

In [88]:
list.sort() #performing sort operation.
print(list)

[23, 45, 89, 90, 100, 100, 200]


In [89]:
list.count(100) #counting number of elements in list.


2

In [90]:
print(list)

[23, 45, 89, 90, 100, 100, 200]


In [91]:
list_reversed=list[: :-1] #reversing the list.
print(list_reversed)


[200, 100, 100, 90, 89, 45, 23]


In [92]:
list.clear() #clearing the list.
print(list)

[]


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.


In [93]:
student=("Raju","Akash","Rajesh") #creating a tuple of 3 strings.
print(student)
type(student)


('Raju', 'Akash', 'Rajesh')


tuple

In [ ]:
student(2,"Bhoomi") #trying to change the value of tuple.
print(student) #we can't change the value of tuple as it is immutable.

TypeError: 'tuple' object is not callable

3.	Create a set of integers with some duplicate values. Print the set and explain the output.



In [99]:
num={1,2,3,4,5,7,3,4,2,4,3,4,5} #creating a set of integers with some duplicate values.
print(num) #It will not print duplicate values as it only stores unique values.

{1, 2, 3, 4, 5, 7}



4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.


In [113]:
Address={'name':"Raju",'age':25,'city':"Bangaluru"}
print(Address)

{'name': 'Raju', 'age': 25, 'city': 'Bangaluru'}


In [ ]:
Address['age']=29 #updating the age.
print(Address)

{'name': 'Raju', 'age': 29, 'city': 'Bangaluru'}


In [ ]:
Address["email"]="raju@gmail.com" #adding new key email.
print(Address)

{'name': 'Raju', 'age': 29, 'city': 'Bangaluru', 'email': 'raju@gmail.com'}


5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [118]:
age=int(input("Enter the age."))
if age>=18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")


You are eligible to vote.


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [126]:
marks=int(input("Enter the marks"))
if marks>=90:
    print("A")
elif marks>=75 and marks<89:
    print("B")
elif marks>=50 and marks<74:
    print("C")
else:
    print("Fail")



C


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [134]:
number=int(input("Enter the number"))
if number>0 and number%2==0:
    print(f"{number} is positive and even")
elif number<0:
    print(f"{number} is negative")
else:
    print("number is zero")




-9 is negative


Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10



In [135]:
import numpy as np
scalar=np.array(5)
print(scalar)

5


In [136]:
array_1d=np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [139]:
array_2d=np.array([10,20,30,40,50,60]).reshape(2,3)
print(array_2d) #rehaped to 2 rows and 3 columns.

[[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [156]:
array_4d=np.random.randint(0,100,size=(4,4))
print(array_4d)

[[98 84 44 30]
 [81 52 11 37]
 [28 32 51  3]
 [25 35 71 61]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [157]:
array_2d=np.array([1,2,3,4,5,6]).reshape(2,3)
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
import pandas as pd #converting array into dataframe.
data=pd.DataFrame(array_2d)
print(data)

   0  1  2
0  1  2  3
1  4  5  6


In [ ]:
data=pd.DataFrame(array_2d,columns=["A","B","C"]) #adding column names to dataframe.
print(data)

   A  B  C
0  1  2  3
1  4  5  6


Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [215]:
Student=pd.DataFrame({'Name':['Raju','Pk','Rakesh','Rajesh','Ramya','Rachita','Uv','Manu','Anu','Pk'],
                      'Age':[25,26,24,35,21,19,22,20,23,26],
                      'City':['Mangalore','Udupi','Mumbai','Rajastan','Andra','Up','Kerala','Mp','Goa','Udupi'],
                      'Salary':[20000,19000,56000,np.nan,10000,11000,np.nan,34000,15000,19000]})
print(Student)

      Name  Age       City   Salary
0     Raju   25  Mangalore  20000.0
1       Pk   26      Udupi  19000.0
2   Rakesh   24     Mumbai  56000.0
3   Rajesh   35   Rajastan      NaN
4    Ramya   21      Andra  10000.0
5  Rachita   19         Up  11000.0
6       Uv   22     Kerala      NaN
7     Manu   20         Mp  34000.0
8      Anu   23        Goa  15000.0
9       Pk   26      Udupi  19000.0


In [ ]:
Student.info() #information.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [ ]:
Student.describe() #descriptive.

Age        Salary
count  10.000000      8.000000
mean   24.100000  23000.000000
std     4.532598  15250.292737
min    19.000000  10000.000000
25%    21.250000  14000.000000
50%    23.500000  19000.000000
75%    25.750000  23500.000000
max    35.000000  56000.000000

In [ ]:
Student_1=Student.drop('City',axis=1) #dropping the column City.
print(Student_1)

      Name  Age   Salary
0     Raju   25  20000.0
1       Pk   26  19000.0
2   Rakesh   24  56000.0
3   Rajesh   35      NaN
4    Ramya   21  10000.0
5  Rachita   19  11000.0
6       Uv   22      NaN
7     Manu   20  34000.0
8      Anu   23  15000.0
9       Pk   26  19000.0


In [ ]:
import warnings
warnings.filterwarnings('ignore') #removing warning messages.

Student['Salary'].fillna(Student['Salary'].mean(),inplace=True) #filling null values.
print(Student)

      Name  Age       City   Salary
0     Raju   25  Mangalore  20000.0
1       Pk   26      Udupi  19000.0
2   Rakesh   24     Mumbai  56000.0
3   Rajesh   35   Rajastan  23000.0
4    Ramya   21      Andra  10000.0
5  Rachita   19         Up  11000.0
6       Uv   22     Kerala  23000.0
7     Manu   20         Mp  34000.0
8      Anu   23        Goa  15000.0
9       Pk   26      Udupi  19000.0


In [ ]:
Student=Student.drop_duplicates() #removing duplicate values.
print(Student)

      Name  Age       City   Salary
0     Raju   25  Mangalore  20000.0
1       Pk   26      Udupi  19000.0
2   Rakesh   24     Mumbai  56000.0
3   Rajesh   35   Rajastan  23000.0
4    Ramya   21      Andra  10000.0
5  Rachita   19         Up  11000.0
6       Uv   22     Kerala  23000.0
7     Manu   20         Mp  34000.0
8      Anu   23        Goa  15000.0
